config/routes.rb
GoldGlory::Application.routes.draw do

  get "coaches/seed"

  get "coaches/buy"
   
  
  get "users/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/tpspend', :to => "pages#tpspend"
  match '/admin_dashboard', :to => "pages#admin_dashboard"
  match '/marketplace', :to => "pages#marketplace"
  

  resources :users

  resources :sessions, :only => [:new, :create, :destroy]

  resources :spamposts do
    post :create
  end

  resources :coaches do
  	member do
  		get :name_edit
  	end
  end

  resources :athletes do
    member do
      post :create
      get :name_edit
    end
  end
  

  match '/generate', :to => 'gamestate#generate_athletes'
  match '/activate_creation', :to => 'gamestate#activate_creation'
  match '/deactivate_creation', :to => 'gamestate#deactivate_creation'
  match '/activate_help_tips', :to => 'gamestate#activate_help_tips'
  match '/seed_unemployed_pool', :to => 'gamestate#seed_unemployed_pool'
  match '/deactivate_help_tips', :to => 'users#deactivate_help_tips'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"

end

app/views/shared/_athlete_form.html.erb
<%= form_for @athlete, :remote => true do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= f.hidden_field(:user_id, :value => current_user.id)  %>

  <div class="field">
    <%= f.label :gender %><br />
    <%= select(:athlete, :gender, [['Male'], ['Female']]) %>
    </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= select(:athlete, :age, [['Normal', 1], ['Young', 2], ['Old', 3]]) %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= select(:athlete, :height, [['Normal', 1], ['Short', 2], ['Tall', 3]]) %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= select(:athlete, :weight, [['Normal', 1], ['Light', 2], ['Heavy', 3]]) %>
  </div>
  <div class="field">
    <%= f.label :skill %><br />
    <%= select(:athlete, :skill, [['Scrub'], ['Amateur'], ['Prodigy']]) %>
  </div>
<div class="field">
<p class = "tp_cost">5</p>
</div>
 <div class="field">
    <%= f.submit "Create" %>
  </div>
<div id="jq_result">
 <p id="jq2"></p>
</div>
 <script>
   function addTotal() {
   var counter1 = $("#athlete_age").val();
   var counter2 = parseInt(counter1);
   $("#jq_result").html('The Age number is '+counter2);

   }

   $("#athlete_age").keyup(function() {
   addTotal();

   });
 </script>

<% end %>

app/views/shared/_athlete_item.html.erb
<%= athlete.name %>

app/views/shared/_athlete_name_edit.html.erb
<div id="athlete_tp_block">
  <div class="name_edit">
    <%= form_for @athlete, :remote => true do |f| %>
    <ul>
      <li>Name         <br />
	<%= f.text_field :first_name %> <%= f.text_field :name %><br />
      </li>

      <li>
  <%= f.submit "Submit Changes" %>
    </li>
 </ul>
</div>
</div>
<% end %>

app/views/shared/_athlete_tp_edit.html.erb
<div id="athlete_tp_block">
<div id="athlete_tp">
<%= form_for @athlete, :remote => true do |f| %>
  <ul>
    <li>Gender         <br />
      <%= @athlete.gender =%></lt>
   <li>Age         <br />
     <%= select(:athlete, :age, [['Normal', 1], ['Old', 2], ['Young', 3]], {:selected => @edathlete.age}) %></li>
   <li>Weight         <br /> 
     <%= select(:athlete, :weight, [['Normal', 1], ['Light', 2], ['Heavy', 3]], {:selected => @edathlete.weight}) %></li>
   <li>Skill         <br />
     <%= select(:athlete, :skill, [['Amateur', 1], ['Scrub', 2], ['Prodigy', 3]], {:selected => @edathlete.skill}) %></li>
   <li>Height         <br />
 <%= select(:athlete, :height, [['Normal', 1], ['Short', 2], ['Tall', 3]], {:selected => @edathlete.height}) %>

</li>
   <li>
  <%= f.submit "Submit Changes" %>
    </li>
   <li id="tp_cost">
   </li>
   <script>

function calc_tp_cost() {
    var skill_value2 = $("#athlete_skill").val();
	var weight_penalty = $('#athlete_weight').val();
	var height_penalty = $('#athlete_height').val();
	var age_penalty = $('#athlete_age').val();
	var penalty_points = 0;
	
	
	

	

    if (skill_value2 == 1) {
		skill_value2 = 20;
    }
    else if (skill_value2 == 2) {
		skill_value2 = 10;
    }
    else {
		skill_value2 = 50;
    }


    if (weight_penalty == 2) {
		penalty_points = 5;
    }
    else if (weight_penalty == 3) {
		penalty_points -=5;
     }
    
    
    if (height_penalty == 2) {
    	penalty_points -=5;
    }
    else if (height_penalty == 3) {
    	penalty_points +=5;
    }
    
    if (age_penalty == 2) {
    	penalty_points -=5;
    }
    else if (age_penalty == 3) {
    	penalty_points +=5;
    }
    
	var total_cost = skill_value2 + penalty_points;
 
    $('#tp_cost').html(""+total_cost);
    
    tp_spent_total();

}

$('#athlete_skill').change(calc_tp_cost);
$('#athlete_weight').change(calc_tp_cost);
$('#athlete_height').change(calc_tp_cost);
$('#athlete_age').change(calc_tp_cost);


calc_tp_cost();
   </script>

 </ul>
</div>
</div>
<% end %>

app/views/shared/_derp.html.erb
<h2>DERP</h2>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>  from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_next_event.html.erb
<div class="next_event_icon">
  <img src="/images/events/1.png">
</div>
<div class="next_event">
  <h2 class="next_event">Next Event</h2><br/>
<p>EAA Championships <br> Marseille, France - 
  26th June, 2011</p>

</div>

app/views/shared/_results.erb
<div id="results_content">
	<ul class="medal_table"><li>Italy</li> <li>China</li></ul>
</div>

app/views/shared/_roster.html.erb
<div>
<% unless @roster_items.empty? %>
<%= render :partial => 'shared/roster_item', :collection =>
@roster_items %>
<% end %>
</div>

app/views/shared/_roster_item.html.erb
<script>
$(document).ready(function() {
	tp_spent_total();

  $(<%= h("edit_") + h(roster_item.id) %>).hide();
  $(<%= h("name_") + h(roster_item.id) %>).hide();});
</script>

<div id=<%= roster_item.id %> class = "roster_item">
	<%= render :partial => 'shared/roster_item_filler', :locals => { :roster_item => roster_item } %>
</div>	

app/views/shared/_roster_item_filler.html.erb
	<div id=<%= h("pic_") + h(roster_item.id) %> class="roster_icon">
		<% if roster_item.gender == "Male" %>
  			<img id="athlete_portrait"
		src=<%=h("/images/athletes/male/") + h(roster_item.iconno) + h(".png") %>>

  		<% else %>
<img id="athlete_portrait"
		src=<%=h("/images/athletes/female/") + h(roster_item.iconno) + h(".png") %>>
		<% end %>
	</div>
	
	<div id=<%= h("stats_") + h(roster_item.id) %> class="roster_stats">
  <ul>
    <li>
      <% if creation_mode? %>
      
      <%= link_to h(roster_item.first_name), name_edit_athlete_path(roster_item.id), :remote => true, :class =>"tp_link" %> <span class="underlined"></span>     <%= link_to h(roster_item.name), name_edit_athlete_path(roster_item.id), :remote => true, :class =>"tp_link" %>

      
      <% else %>
      <%= roster_item.name %>

      <% end %>

	  
<br/>Gender: <%= roster_item.gender =%>
       <br />
    Age: 
     <% if roster_item.age == 1 %>
     Normal

     <% elsif roster_item.age == 2 %>
     Old
     <% else %>
     Young 
     <% end %>

 </li>
     <li>
 Weight:     
     <% if roster_item.weight == 1 %>
     Normal

     <% elsif roster_item.weight == 2 %>
     Light
     <% else %>
     Heavy
     <% end %>
<br />
 Height:     
     <% if roster_item.height == 1 %>
     Normal

     <% elsif roster_item.height == 2 %>
     Short
     <% else %>
     Tall
     <% end %>
<br />
   Skill:    
     <% if roster_item.skill == 1 %>
     <span id="silver_text">Amateur</span>
     
     <% elsif roster_item.skill == 2 %>
     <span id="bronze_text">Scrub</span>
     <% else %>
     <span id="gold_text">Prodigy</span>
     <% end %>
</li><li>
   <% if creation_mode? %>
   <img src="images/tp.png"><br />
   <%= link_to "Edit TPs", edit_athlete_path(roster_item.id), :remote => true, :class =>"tp_link" %>
   </li>
<li>
     <p class="tps_spent"><%= roster_item.tps %></p>
</li>
<li>
	<p class="penalty_tps"><%= roster_item.penalty_tps %></p>
	</li>
<% end %>
  </ul>
  </div>

<div id=<%= h("edit_") + h(roster_item.id) %> class="edit_panel"></div>
<div id=<%= h("name_") + h(roster_item.id) %> class="name_edit_panel"></div>

app/views/shared/_spamfeed.html.erb
<div id="spamfeed">
<p id="spambox_title">SpamBox</p>
<div id="spamfeed_contents">
<% unless @spamfeed_items.empty? %>
<%= render :partial => 'shared/spamfeed_item', :collection =>
@spamfeed_items %>
</div>
<% end %>
</div>

app/views/shared/_spamfeed_item.html.erb
<div id="spamfeed_item">
  <ul>
   <li><%= spamfeed_item.content =%></li>
    <li><span id="posted_at"><%= time_ago_in_words(spamfeed_item.created_at) %>
    ago by <%= spamfeed_item.user.name.capitalize =%></span></li>
  </ul>

</div>

app/views/shared/_tab_bar.html.erb
<div id="tab_bar">

    <% if signed_in? %>
    <% if creation_mode? %>

    <div class="tab_button" id="tab_button1">
      <script>
	$('#tab_button1').mouseenter(function() {
	$(this).animate({top:'2px', height:'33px'},"fast");
	});

	$('#tab_button1').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
      <%= link_to "Creation", "/tpspend" %>
    </div>
    <% end %>
    
    <div class="tab_button" id="tab_button2">
      <script>
	$('#tab_button2').mouseenter(function() {
	
	$(this).animate({top:'2px', height:'33px'},"fast");
	});
	
	$('#tab_button2').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
      <%= link_to "Home", root_path %>
    </div>
   
    <div class="tab_button" id="tab_button3">
      <script>
	$('#tab_button3').mouseenter(function() {
	
	$(this).animate({top:'2px', height:'33px'},"fast");
	});
	
	$('#tab_button3').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
      <%= link_to "Training", root_path %>
    </div>
    
    <div class="tab_button" id="tab_button6">
      <script>
	$('#tab_button6').mouseenter(function() {
	
	$(this).animate({top:'2px', height:'33px'},"fast");
	});
	
	$('#tab_button6').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
      <%= link_to "Staff", root_path %>
    </div>    
    
    <div class="tab_button" id="tab_button4">
      <script>
	$('#tab_button4').mouseenter(function() {
	
	$(this).animate({top:'2px', height:'33px'},"fast");
	});
	
	$('#tab_button4').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
      <%= link_to "Marketplace", '/marketplace' %>
    </div>
    
 
     <div class="tab_button" id="tab_button5">
      <script>
	$('#tab_button5').mouseenter(function() {
	
	$(this).animate({top:'2px', height:'33px'},"fast");
	});
	
	$('#tab_button5').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
      <%= link_to "Espionage", root_path %>
    </div>
           

   <% if admin? %>
    <div class="tab_button" id="tab_button8">
      <script>
	$('#tab_button8').mouseenter(function() {
	
	$(this).animate({top:'2px', height:'33px'},"fast");
	});
	
	$('#tab_button8').mouseleave(function() {
	$(this).animate({top:'5px', height:'30px'},"fast");
	});
      </script>
     <li><%= link_to "Admin", '/admin_dashboard' %></li>  

     </div>
          

  <% end %>
  <% end %>

</div>