config/routes.rb
GoldGlory::Application.routes.draw do

  get "coaches/seed"

  get "coaches/buy"
   
  
  get "users/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/tpspend', :to => "pages#tpspend"
  match '/admin_dashboard', :to => "pages#admin_dashboard"
  match '/marketplace', :to => "pages#marketplace"
  

  resources :users

  resources :sessions, :only => [:new, :create, :destroy]

  resources :spamposts do
    post :create
  end

  resources :coaches do
  	member do
  		get :name_edit
  	end
  end

  resources :athletes do
    member do
      post :create
      get :name_edit
    end
  end
  

  match '/generate', :to => 'gamestate#generate_athletes'
  match '/activate_creation', :to => 'gamestate#activate_creation'
  match '/deactivate_creation', :to => 'gamestate#deactivate_creation'
  match '/activate_help_tips', :to => 'gamestate#activate_help_tips'
  match '/seed_unemployed_pool', :to => 'gamestate#seed_unemployed_pool'
  match '/deactivate_help_tips', :to => 'users#deactivate_help_tips'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"

end

app/views/pages/_tpspend.html.erb
<div id="athlete_creator_container">
<h1>Spend those talent points!</h1>
<%= render '/shared/athlete_form' %>
</div>

app/views/pages/about.html.erb
<div id="sign_in_page_container">

<div id="sign_in_container">
  <div id="sign_in_content">
    <h1>About</h1>
<p class="descriptive">Ask Conrad. I'm just a website</p>
</div>
</div>
</div>

app/views/pages/admin_dashboard.html.erb
<div id="upper_block">


<div id="next_event_container">
  <%= render 'shared/next_event' %>
</div>

      

<div id ="results_container">
  <%= render 'shared/results' %>
</div>
</div>

<div id="lower_block">      
      <div id = "tab_bar_container">
	<%= render 'shared/tab_bar' %>
      </div>

<div id = "content_container">

<div class="left_content">
 <h1>All users</h1>

<%= will_paginate @users %>
<ul class="users">
  <%= render @users %>
</ul>
</div>
<div class="right_content">
  <div class="admin_right_content">
    <p>Stuff here</p>
    <%= link_to 'Generate Stats', :controller => 'gamestate', :action => 'generate_athletes' %>
<br/>
    <%= link_to 'View Athletes', athletes_path %><br>
    <%= link_to 'Activate Creation Mode', :controller => 'gamestate', :action => 'activate_creation' %><br>
    <%= link_to 'Dectivate Creation Mode', :controller => 'gamestate', :action => 'deactivate_creation' %><br>
	<%= link_to 'Turn on Help Tips', :controller => 'gamestate', :action => 'activate_help_tips' %><br><br>
	<%= link_to 'Seed Employment Pool', :controller => 'gamestate', :action => 'seed_unemployed_pool' %><br>




  </div>
</div>
  
</div>

<div id="spam_container">
  <%= render '/shared/spamfeed' %>
  
  <%= render '/shared/spampost_form' %>
</div>


</div>

app/views/pages/contact.html.erb
<div id="sign_in_page_container">

<div id="sign_in_container">
  <div id="sign_in_content"><h1>Contact Us</h1>
<p class="descriptive"><a href="mailto:zeussoid@hotmail.com">email Conrad</a>
  or <a href="mailto:jlswaine@me.com">email John Louis</a>.</p>
</div>
</div>
</div>

app/views/pages/home.html.erb
<div id="upper_block">
<div id="next_event_container">
  <%= render 'shared/next_event' %>
</div>


<div id ="results_container">
  <%= render 'shared/results' %>
</div>

<div id ="lower_block">

<div id ="tab_bar_container">
   <% if signed_in? %>

  <%= render 'shared/tab_bar' %>
	  <% end %>

</div>



<div id="spam_container">
  <% if signed_in? %>
<% if help_tips? %>
<div id="help_box_spam">
	<h1>SpamBox</h1>
 <p class="welcome_text">The SpamBox is like an internal twitter feed for Gold and Glory. Post a message and it'll turn up here for other players to read.</p> <div class="button_row"> <button id="hide_spam">Got it! Now go away...</button> <%= button_to "Turn Off Help Tips", :controller => 'users', :action => "deactivate_help_tips", :remote => true %></div></div>
<% end %>
  <%= render '/shared/spamfeed' %>
  
  <%= render '/shared/spampost_form' %>
    <% end %>

</div>

<div id = "content_container">
  <% if signed_in? %>
  
  <h1>Welcome to Gold and Glory</h1> 
  
  <% if creation_mode? %>
  <h2>Creation Mode Active!</h2>
  <% end %>
  <p class="welcome_text">"As a new coach, you've been seeded with a roster of your nation's current Athletic talent. You can use the Talent Points you've been granted to make your athletes more skillful. 
  However, there aren't many points to spend. If you want more you'll have to earn them by removing attributes from other athletes."</p>
  
 



<% else %>
<div>
  <h1>Gold and Glory is under development</h1>
  <div id ="logo_image">
    <img src="/images/logo.jpg">
  </div>
  
  <span class="huge descriptive"><p><%= link_to "Sign Up", users_new_path %></p>
    <p>or</p>
    <p><%= link_to "Sign In", signin_path %></p></span>


  <% end %>
  
<script>



	$(".help_tips_off").click(function(){
		
		user.help_tips = false;

	}
	);

  $("#hide_spam").click(function(){

		$("#help_box_spam").animate({"left": "+=500px"}, 400, function(){
  			$("#help_box_spam").animate({"opacity": 0}, 1); 
  			}
  			)
  			}
  			);
  
  </script>  
  
</div>
</div>

app/views/pages/marketplace.html.erb
<div id="upper_block">
<div id="next_event_container">
  <%= render 'shared/next_event' %>
</div>
<div id="testr"><img src="/images/coaches/male/1.png"></div>

<% if signed_in? %>


<div id ="results_container">
  <%= render 'shared/results' %>
</div>

<div id ="lower_block">

<div id ="tab_bar_container">

  <%= render 'shared/tab_bar' %>

</div>

<div id="spam_container">

  <%= render '/shared/spamfeed' %>
  
  <%= render '/shared/spampost_form' %>

</div>

<div id = "content_container">
  
  <div id="junior_coach_container">
	<p id="junior_coach_title">Hire a Junior Coach</p>
	<%= form_for @coach, :remote => true do |f| %>
	<span class="roster_stats"><ul><li>Name:  <br /><%= f.text_field :name %></li>
	 
	 <li>Event:  <br /> <%= select(:coach, :event, [['Athletics - Field', 'Athletics - Field'], ['Athletics - Track', 'Athletics - Track'], ['Swimming', 'Swimming'], ['Shooting', 'Shooting'], ['Weightlifting', 'Weightlifting'], ['Judo', 'Judo'], ['Rowing', 'Rowing'], ['Cycling', 'Cycling'], ['Gymnastics', 'Gymnastics'], ['Boxing', 'Boxing'], ['Equestrian', 'Equestrian'], ['Diving', 'Diving'], ['Canoeing', 'Canoeing'], ['Taekwondo', 'Taekwondo'], ['Fencing', 'Fencing'], ['Sailing', 'Sailing']], {:selected => @coach.event}) %></li>
	  <li>Level:  <br /> 
     <%= select(:coach, :level, [['1', 1], ['2', 2], ['3', 3]], {:selected => @coach.level}) %></li>
     <li>Cost: <br /> $<span id="cash_cost">5</span>k</li>
	<li><%= f.submit "Purchase" %>
</li>

	</ul>
	</span>
	<% end %>
</div>

</div>


<% else %>
<div>
  <h1>Gold and Glory is under development</h1>
  <div id ="logo_image">
    <img src="/images/logo.jpg">
  </div>
  
  <span class="huge descriptive"><p><%= link_to "Sign Up", users_new_path %></p>
    <p>or</p>
    <p><%= link_to "Sign In", signin_path %></p></span>


 <% end %>
  
</div>
</div>



<script>

function calc_cash_cost() {

    var level_value = $("#coach_level").val();
	
	var total_cost = level_value * 5
    
    
     $('#cash_cost').html(""+total_cost);

}


function testr_hide() {

	$("#testr").animate({"top": "+=300px"}, 1500);

}

$('#coach_level').change(calc_cash_cost);

function para_coach() {
 $("#testr").animate({"top":-64, "opacity": 1}, 0, function() { 
  $("#testr").animate({"top": "+=270px"}, 1300, function(){
  	$("#testr").animate({"opacity": 0}, 100, function() {
  		$("#testr").animate({"top":-64, "opacity": 1}, 0) }) })
  	});

  }



$("#testbutton").click(function(){

  $("#testr").animate({"top": "+=270px"}, 1300, function(){
  	$("#testr").animate({"opacity": 0}, 100);

  }
  );

  
});



</script>

app/views/pages/tpspend.html.erb
<div id="upper_block">

<div id="next_event_container">
  <div class="next_event_content">
    <%= render 'shared/next_event' %>
  </div>
</div>
  

<div id ="results_container">
  <%= render 'shared/results' %>
</div>

</div>

<div id = "tp_total_container">
	<div id = "tp_total_content">
	  <div id = "tp_total_board">
  		<p><span id="live_tp_tally" class="fat_white"></span></p>
	  </div>
	  <div id = "refund_total_board" class="refund_underspent">
  		<p><span id="live_refund_text">Refunds</span><span id="live_refund_tally">2</span></p>
	  </div>

	</div>	
</div>


<div id="lower_block">    

<div id = "tab_bar_container">
  <%= render 'shared/tab_bar' %>
</div>


<% if help_tips? %>
<div id="help_box_1">
	<h1>Help Tip</h1>
 <p class="welcome_text">Spend and re-distribute talent points till you achieve equillibrium and the 'TP spent' indicator turns green with a Tick-Mark (<img src="/images/pt_left_pointer_green_small.png">). 
  You can come back to this page and change your athletes at any point before stats are rolled. </p> <div class="button_row"> <button id="hide_1">Got it! Now go away...</button><%= button_to "Turn Off Help Tips", {:controller => 'users', :action => "deactivate_help_tips"}, :class => 'hide_help_tips_button', :remote => true %></div></div>
<% end %>


<div id = "content_container">
  <h1>Spend those talent points!</h1>

  <script>

    function refund_total() {
    var refundspent = 0;
   $(".penalty_tps").each(function() {
  			refundspent += Number($(this).text());  			
 		}); 
	  		$("#live_refund_tally").text(""+refundspent);

      		if (refundspent > 40) {
			$('#refund_total_board').removeClass('refund_underspent');
  			$('#refund_total_board').addClass('refund_overspent');
    }
    else {
			$('#refund_total_board').removeClass('refund_overspent');
  			$('#refund_total_board').addClass('refund_underspent');
    }
    };


   function tp_spent_total() {
   		console.log("TPspentTotalcalled");
   refund_total();
		
    var tpsspent = 0;
  		var tpleft = 500;
  		$(".tps_spent").each(function() {
  			tpsspent += Number($(this).text());  			
  			// OR new var = tpspent -500. Test best.
  		}); 
  		tpleft -= tpsspent
  		if (tpleft > 0) {
	  		$("#live_tp_tally").text(""+tpleft +"  Unspent TPs");
  			$('#tp_total_board').removeClass('tp_overspent');
  			$('#tp_total_board').removeClass('tp_perfect');

			$('#tp_total_board').addClass('tp_underspent');


   


  		}
  		else if (tpleft < 0) {
  			$("#live_tp_tally").text(""+tpleft +" TPs");
  			$('#tp_total_board').removeClass('tp_underspent');
  			$('#tp_total_board').removeClass('tp_perfect');

			$('#tp_total_board').addClass('tp_overspent');




  		}
  		
  		else {
  			$("#live_tp_tally").text("");
  			$('#tp_total_board').removeClass('tp_underspent');
  			$('#tp_total_board').removeClass('tp_overspent');

			$('#tp_total_board').addClass('tp_perfect');


  		}
  		
	};
	
	

	$(document).ready(function() {
		var top = $('#tp_total_content').offset().top - parseFloat($('#tp_total_content').css('marginTop'));
		$(window).scroll(function() {
		//
		///document.getElementById(controlId).offsetTop
	
			// find the y position of the scroll

// as of 1.4.2 the mobile safari reports wrong values on offset()
// http://dev.jquery.com/ticket/6446
// remove once it's fixed
		
		var	y = $(this).scrollTop();
		
		
		if((navigator.userAgent.match(/iPad/i))) {
  			y -= window.scrollY;
       	};
				
			
			if (y >= top) {
				$('#tp_total_content').addClass('fixed');
			}
			else {
				$('#tp_total_content').removeClass('fixed');
			}
			// if so add fixed
			
			
			// else remove
		});
	});
   
  $("#hide_1").click(function(){

		$("#help_box_1").animate({"left": "-=500px"}, 400, function(){
  			$("#help_box_1").animate({"opacity": 0}, 1); 
  			}
  			)
  			}
  			);
  
  </script>
  

  
  <div id="roster_container">
    <h3>Your Roster</h3>
    <%= render '/shared/roster' %>
  </div> 
  
</div>

<div id="spam_container">
  <%= render '/shared/spamfeed' %>
  
  <%= render '/shared/spampost_form' %>
</div>



</div>

app/views/pages/tpspend.js.erb
$("#content_container").html("<%= escape_javascript(render :partial => '/pages/tpspend', :locals =>{:collection => @roster_items}) %>")