config/routes.rb
GoldGlory::Application.routes.draw do

  get "coaches/seed"

  get "coaches/buy"
   
  
  get "users/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/tpspend', :to => "pages#tpspend"
  match '/admin_dashboard', :to => "pages#admin_dashboard"
  match '/marketplace', :to => "pages#marketplace"
  

  resources :users

  resources :sessions, :only => [:new, :create, :destroy]

  resources :spamposts do
    post :create
  end

  resources :coaches do
  	member do
  		get :name_edit
  	end
  end

  resources :athletes do
    member do
      post :create
      get :name_edit
    end
  end
  

  match '/generate', :to => 'gamestate#generate_athletes'
  match '/activate_creation', :to => 'gamestate#activate_creation'
  match '/deactivate_creation', :to => 'gamestate#deactivate_creation'
  match '/activate_help_tips', :to => 'gamestate#activate_help_tips'
  match '/seed_unemployed_pool', :to => 'gamestate#seed_unemployed_pool'
  match '/deactivate_help_tips', :to => 'users#deactivate_help_tips'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<div class="footer"><p>Copyright Conrad Williams & John Louis Swaine 2011</p></div>

app/views/layouts/_header.html.erb
<nav>
<ul>

  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Contact Us", contact_path %></li>
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Users", users_path %></li>
  <% if signed_in? %>
  <% if admin? %>
  <li><%= link_to "Admin Dashboard", '/admin_dashboard' %></li>
  <% end %>
  <li><%= link_to "Sign Out", signout_path, :method => 
    :delete %></li>
  <% else %>
  <li><%= link_to "Sign In", signin_path %></li>
  <% end %>

</ul>
</nav>

app/views/layouts/_sign_path.html.erb
<% if signed_in? %>
<li><%= link_to "Sign Out", destroy_session_path, :method => :delete %></li>
<% else %>
<li><%= link_to "Sign In", new_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
   <%= stylesheet_link_tag 'custom',  :media => 'screen' %>

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" %>
<%= javascript_include_tag 'rails' %>
<%= csrf_meta_tag %>
</head>
<body>

<div id="page_container">
  <%= render 'layouts/header' %>
 <script>

   $('#athlete_age').keyup(function() {   });
 </script>


<%= yield %>
  	        <% flash.each do |key, value| %>
          		<%= content_tag(:div, value, :class => "flash #{key}") %>
	        <% end %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>